var lay_id = layer_get_id("Backgrounds_1")
var back_id = layer_background_get_id(lay_id)
var lay_id2 = layer_get_id("Backgrounds_2")
var back_id2 = layer_background_get_id(lay_id2)
var lay_id3 = layer_get_id("Backgrounds_3")
var back_id3 = layer_background_get_id(lay_id3)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 963)
    layer_background_sprite(back_id, bg_castle3escape)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 960)
    layer_background_sprite(back_id, bg_castle4escape)
if (global.panic == 1 && layer_background_get_sprite(back_id3) == 965)
    layer_background_sprite(back_id3, bg_castle1escape)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 929)
    layer_background_sprite(back_id, bg_factory3escape)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 932)
    layer_background_sprite(back_id, bg_factory1escape)
if (global.panic == 1 && layer_background_get_sprite(back_id2) == 934)
    layer_background_sprite(back_id2, bg_factory2escape)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1000)
    layer_background_sprite(back_id, bg_sewer1escape)
if (global.panic == 1 && layer_background_get_sprite(back_id2) == 998)
    layer_background_sprite(back_id2, bg_sewer2escape)
if (global.panic == 1 && layer_background_get_sprite(back_id3) == 996)
    layer_background_sprite(back_id3, bg_sewer3escape)
